name: Resource Adaptive Jupyter Notebook Processing

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use for notebook execution'
        required: true
        type: string
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use for notebook execution'
        required: true
        type: string

env:
  MEMORY_THRESHOLD: 80      # Percentage
  DISK_THRESHOLD_MB: 500    # Minimum available disk space in MB

jobs:
  discover-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Jupyter Notebooks
        id: set-matrix
        run: |
          # Find all .ipynb files recursively under notebooks/
          NOTEBOOKS=$(find notebooks/ -type f -name "*.ipynb" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          # Format as JSON matrix
          MATRIX_JSON=$(echo "$NOTEBOOKS" | jq -c '{args: .}')
          
          # Set output - escape newlines and quotes properly
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  process-notebooks-standard:
    needs: discover-notebooks
    strategy:
      matrix: ${{ fromJson(needs.discover-notebooks.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.standard-run.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Jupyter and Monitoring Tools
        run: |
          pip install jupyter nbconvert psutil

      - name: Install Notebook Requirements
        run: |
          NOTEBOOK_DIR=$(dirname "${{ matrix.args }}")
          REQUIREMENTS="$NOTEBOOK_DIR/requirements.txt"
          if [ -f "$REQUIREMENTS" ]; then
            pip install -r "$REQUIREMENTS"
          else
            echo "No requirements.txt found in $NOTEBOOK_DIR, skipping dependency installation"
          fi

      - name: Run Notebook with Resource Monitoring (Standard)
        id: standard-run
        continue-on-error: true
        run: |
          # Create a monitoring script for memory and disk
          cat << 'EOF' > monitor_resources.py
          import psutil
          import os
          import sys
          import time

          def monitor_resources(pid, threshold_mem, threshold_disk_mb, interval=1):
              process = psutil.Process(pid)
              max_mem = 0
              min_disk_mb = float('inf')
              notebook_dir = os.path.dirname(sys.argv[4])  # Get notebook directory from args
              while psutil.pid_exists(pid):
                  try:
                      mem = process.memory_percent()
                      disk = psutil.disk_usage(notebook_dir)
                      available_mb = disk.free / (1024 * 1024)  # Convert bytes to MB
                      max_mem = max(max_mem, mem)
                      min_disk_mb = min(min_disk_mb, available_mb)
                      if mem > threshold_mem or available_mb < threshold_disk_mb:
                          print(f"Resource exceeded: Memory {mem:.1f}% (max {max_mem:.1f}%) > {threshold_mem}%, Disk available {available_mb:.1f}MB (min {min_disk_mb:.1f}MB) < {threshold_disk_mb}MB")
                          sys.exit(1)
                      time.sleep(interval)
                  except psutil.NoSuchProcess:
                      break
              print(f"Max resources used: Memory {max_mem:.1f}%, Min disk available {min_disk_mb:.1f}MB")
              return max_mem, min_disk_mb

          if __name__ == "__main__":
              pid = int(sys.argv[1])
              threshold_mem = float(sys.argv[2])
              threshold_disk_mb = float(sys.argv[3])
              monitor_resources(pid, threshold_mem, threshold_disk_mb)
          EOF

          # Run notebook in background and monitor resources
          jupyter nbconvert --to notebook --execute "${{ matrix.args }}" &
          NOTEBOOK_PID=$!
          
          # Start monitoring, passing notebook path as additional arg
          python monitor_resources.py $NOTEBOOK_PID ${MEMORY_THRESHOLD} ${DISK_THRESHOLD_MB} "${{ matrix.args }}"
          
          # Wait for notebook process to complete and get its exit code
          wait $NOTEBOOK_PID
          NOTEBOOK_EXIT_CODE=$?
          
          # If notebook failed for reasons other than resources, fail the step
          if [ $NOTEBOOK_EXIT_CODE -ne 0 ]; then
            echo "Notebook execution failed with exit code $NOTEBOOK_EXIT_CODE"
            exit 1
          fi

  process-notebooks-16gb-cleanup:
    needs: process-notebooks-standard
    if: needs.process-notebooks-standard.outputs.outcome == 'failure'
    strategy:
      matrix: ${{ fromJson(needs.discover-notebooks.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Determine notebook directory
        id: get-dir
        run: |
          NOTEBOOK_DIR=$(dirname "${{ matrix.args }}")
          echo "notebook_dir=$NOTEBOOK_DIR" >> $GITHUB_OUTPUT
      - name: Clean notebook directory
        run: |
          rm -rf "${{ steps.get-dir.outputs.notebook_dir }}"/*
      - name: Re-checkout repository
        uses: actions/checkout@v3

  process-notebooks-16gb:
    needs: [discover-notebooks, process-notebooks-standard, process-notebooks-16gb-cleanup]
    if: needs.process-notebooks-standard.outputs.outcome == 'failure'
    strategy:
      matrix: ${{ fromJson(needs.discover-notebooks.outputs.matrix) }}
      fail-fast: false
    runs-on: 
      group: jwst-pipeline-notebooks-16gb
    outputs:
      outcome: ${{ steps.medium-run.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Jupyter and Monitoring Tools
        run: |
          pip install jupyter nbconvert psutil
      - name: Install Notebook Requirements
        run: |
          NOTEBOOK_DIR=$(dirname "${{ matrix.args }}")
          REQUIREMENTS="$NOTEBOOK_DIR/requirements.txt"
          if [ -f "$REQUIREMENTS" ]; then
            pip install -r "$REQUIREMENTS"
          else
            echo "No requirements.txt found in $NOTEBOOK_DIR, skipping dependency installation"
          fi
      - name: Run on 16GB runner with Resource Monitoring
        id: medium-run
        continue-on-error: true
        run: |
          # Create monitoring script (same as above)
          cat << 'EOF' > monitor_resources.py
          import psutil
          import os
          import sys
          import time

          def monitor_resources(pid, threshold_mem, threshold_disk_mb, interval=1):
              process = psutil.Process(pid)
              max_mem = 0
              min_disk_mb = float('inf')
              notebook_dir = os.path.dirname(sys.argv[4])  # Get notebook directory from args
              while psutil.pid_exists(pid):
                  try:
                      mem = process.memory_percent()
                      disk = psutil.disk_usage(notebook_dir)
                      available_mb = disk.free / (1024 * 1024)  # Convert bytes to MB
                      max_mem = max(max_mem, mem)
                      min_disk_mb = min(min_disk_mb, available_mb)
                      if mem > threshold_mem or available_mb < threshold_disk_mb:
                          print(f"Resource exceeded: Memory {mem:.1f}% (max {max_mem:.1f}%) > {threshold_mem}%, Disk available {available_mb:.1f}MB (min {min_disk_mb:.1f}MB) < {threshold_disk_mb}MB")
                          sys.exit(1)
                      time.sleep(interval)
                  except psutil.NoSuchProcess:
                      break
              print(f"Max resources used: Memory {max_mem:.1f}%, Min disk available {min_disk_mb:.1f}MB")
              return max_mem, min_disk_mb

          if __name__ == "__main__":
              pid = int(sys.argv[1])
              threshold_mem = float(sys.argv[2])
              threshold_disk_mb = float(sys.argv[3])
              monitor_resources(pid, threshold_mem, threshold_disk_mb)
          EOF

          # Run notebook in background and monitor resources
          jupyter nbconvert --to notebook --execute "${{ matrix.args }}" &
          NOTEBOOK_PID=$!
          
          # Start monitoring, passing notebook path as additional arg
          python monitor_resources.py $NOTEBOOK_PID ${MEMORY_THRESHOLD} ${DISK_THRESHOLD_MB} "${{ matrix.args }}"
          
          # Wait for notebook process to complete and get its exit code
          wait $NOTEBOOK_PID
          NOTEBOOK_EXIT_CODE=$?
          
          # If notebook failed for reasons other than resources, fail the step
          if [ $NOTEBOOK_EXIT_CODE -ne 0 ]; then
            echo "Notebook execution failed with exit code $NOTEBOOK_EXIT_CODE"
            exit 1
          fi

  process-notebooks-32gb-cleanup:
    needs: process-notebooks-16gb
    if: needs.process-notebooks-16gb.outputs.outcome == 'failure'
    strategy:
      matrix: ${{ fromJson(needs.discover-notebooks.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Determine notebook directory
        id: get-dir
        run: |
          NOTEBOOK_DIR=$(dirname "${{ matrix.args }}")
          echo "notebook_dir=$NOTEBOOK_DIR" >> $GITHUB_OUTPUT
      - name: Clean notebook directory
        run: |
          rm -rf "${{ steps.get-dir.outputs.notebook_dir }}"/*
      - name: Re-checkout repository
        uses: actions/checkout@v3

  process-notebooks-32gb:
    needs: [discover-notebooks, process-notebooks-16gb, process-notebooks-32gb-cleanup]
    if: needs.process-notebooks-16gb.outputs.outcome == 'failure'
    strategy:
      matrix: ${{ fromJson(needs.discover-notebooks.outputs.matrix) }}
      fail-fast: false
    runs-on: 
      group: jwst-pipeline-notebooks-32gb
    outputs:
      outcome: ${{ steps.large-run.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Jupyter and Monitoring Tools
        run: |
          pip install jupyter nbconvert psutil
      - name: Install Notebook Requirements
        run: |
          NOTEBOOK_DIR=$(dirname "${{ matrix.args }}")
          REQUIREMENTS="$NOTEBOOK_DIR/requirements.txt"
          if [ -f "$REQUIREMENTS" ]; then
            pip install -r "$REQUIREMENTS"
          else
            echo "No requirements.txt found in $NOTEBOOK_DIR, skipping dependency installation"
          fi
      - name: Run on 32GB runner with Resource Monitoring
        id: large-run
        continue-on-error: true
        run: |
          # Create monitoring script (same as above)
          cat << 'EOF' > monitor_resources.py
          import psutil
          import os
          import sys
          import time

          def monitor_resources(pid, threshold_mem, threshold_disk_mb, interval=1):
              process = psutil.Process(pid)
              max_mem = 0
              min_disk_mb = float('inf')
              notebook_dir = os.path.dirname(sys.argv[4])  # Get notebook directory from args
              while psutil.pid_exists(pid):
                  try:
                      mem = process.memory_percent()
                      disk = psutil.disk_usage(notebook_dir)
                      available_mb = disk.free / (1024 * 1024)  # Convert bytes to MB
                      max_mem = max(max_mem, mem)
                      min_disk_mb = min(min_disk_mb, available_mb)
                      if mem > threshold_mem or available_mb < threshold_disk_mb:
                          print(f"Resource exceeded: Memory {mem:.1f}% (max {max_mem:.1f}%) > {threshold_mem}%, Disk available {available_mb:.1f}MB (min {min_disk_mb:.1f}MB) < {threshold_disk_mb}MB")
                          sys.exit(1)
                      time.sleep(interval)
                  except psutil.NoSuchProcess:
                      break
              print(f"Max resources used: Memory {max_mem:.1f}%, Min disk available {min_disk_mb:.1f}MB")
              return max_mem, min_disk_mb

          if __name__ == "__main__":
              pid = int(sys.argv[1])
              threshold_mem = float(sys.argv[2])
              threshold_disk_mb = float(sys.argv[3])
              monitor_resources(pid, threshold_mem, threshold_disk_mb)
          EOF

          # Run notebook in background and monitor resources
          jupyter nbconvert --to notebook --execute "${{ matrix.args }}" &
          NOTEBOOK_PID=$!
          
          # Start monitoring, passing notebook path as additional arg
          python monitor_resources.py $NOTEBOOK_PID ${MEMORY_THRESHOLD} ${DISK_THRESHOLD_MB} "${{ matrix.args }}"
          
          # Wait for notebook process to complete and get its exit code
          wait $NOTEBOOK_PID
          NOTEBOOK_EXIT_CODE=$?
          
          # If notebook failed for reasons other than resources, fail the step
          if [ $NOTEBOOK_EXIT_CODE -ne 0 ]; then
            echo "Notebook execution failed with exit code $NOTEBOOK_EXIT_CODE"
            exit 1
          fi

  check-final-outcome:
    needs: [process-notebooks-standard, process-notebooks-16gb, process-notebooks-32gb]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Fail if all attempts unsuccessful
        run: |
          if [ "${{ needs.process-notebooks-standard.outputs.outcome }}" = "failure" ] && \
             [ "${{ needs.process-notebooks-16gb.outputs.outcome }}" = "failure" ] && \
             [ "${{ needs.process-notebooks-32gb.outputs.outcome }}" = "failure" ]; then
            echo "Notebook processing failed on all runner sizes for: ${{ matrix.args }}"
            exit 1
          fi
