name: Config Test - Execute Jupyter Notebooks
on:
  workflow_dispatch:

jobs:
  ExecuteNotebooks:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_runner.yml@jwst_pipeline
   with:
      python-version: ${{ vars.PYTHON_VERSION || '3.11' }}
   permissions:
     contents: write
